{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "version", "default": "v2", "conditions": [], "values": ["v1", "v2", "next"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "conv3_depth", "default": 4, "conditions": [], "values": [4, 8], "ordered": true}}, {"class_name": "Choice", "config": {"name": "conv4_depth", "default": 6, "conditions": [], "values": [6, 23, 36], "ordered": true}}, {"class_name": "Choice", "config": {"name": "pooling", "default": "avg", "conditions": [], "values": ["avg", "max"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "rmsprop", "sgd"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.1, 0.01, 0.001], "ordered": true}}], "values": {"version": "v1", "conv3_depth": 8, "conv4_depth": 6, "pooling": "avg", "optimizer": "rmsprop", "learning_rate": 0.1, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 0, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras_tuner/tuners/hyperband.py\", line 425, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras_tuner/engine/tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras_tuner/engine/tuner.py\", line 214, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras_tuner/engine/hypermodel.py\", line 144, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/tmp/__autograph_generated_fileek7uh3l5.py\", line 18, in tf__train_function\n    raise\nValueError: in user code:\n\n    File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras/engine/training.py\", line 1284, in train_function  *\n        return step_function(self, iterator)\n    File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras/engine/training.py\", line 1268, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras/engine/training.py\", line 1249, in run_step  **\n        outputs = model.train_step(data)\n    File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras/engine/training.py\", line 1050, in train_step\n        y_pred = self(x, training=True)\n    File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"/home/birdy/Repos/Jira_Oracle/.venv/lib/python3.11/site-packages/keras/engine/input_spec.py\", line 235, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Exception encountered when calling layer 'ResNet' (type Functional).\n    \n    Input 0 of layer \"conv1_pad\" is incompatible with the layer: expected ndim=4, found ndim=2. Full shape received: (None, 1)\n    \n    Call arguments received by layer 'ResNet' (type Functional):\n      \u2022 inputs=tf.Tensor(shape=(None, 1), dtype=string)\n      \u2022 training=True\n      \u2022 mask=None\n\n"}